### ISSUE TITLE
Removes other interfaces configuration when adding a new one

### ISSUE THREAD

**Issue by odumasFR** [mgeldert/pulse-vtm-ansible#1]
I usually deploy boxes with at least two interfaces: 1 for management (set with z-set-initial-ip-address or template customization), and another for production. When adding configuration for the second, it removes configuration for the first.
In the example below, interfaces are ens160 for management and ens192 for production.

ansible playbook (run when ens160 has an address, obviously) 
[basic_play_issue1.txt](https://github.com/mgeldert/pulse-vtm-ansible/files/1824219/basic_play_issue1.txt)

after playbook run, ens192 has an IP but ens160 isn't configured anymore
I guess it's a REST API problem, but a workaround could be made at ansible level (working on it)

**Comment by mgeldert** [comment]
Thanks for reporting this.  Yes, the problem here is around the way the REST API works; as traffic_manager -> appliance -> ip is a table field and interfaces are rows in the table, any new value for the field you PUT will overwrite the existing table.  The interim workaround I'm sure you've already found is to just include entries for both interfaces in the playbook.  

Building a workaround at the Ansible-level is possible; I would envisage it looking something like this...
```
- name: Create new vTM Config
  hosts: vtms
  tasks:
    - name: Define production interfaces
      traffic_manager:
        name: testvADC
        password: password```
        append_to_tables: 
            appliance:
              - ip
        properties:
          appliance:
            manageiptrans: True
            ip:
              - name: "ens192"
                addr: "172.16.0.1"
                isexternal: True
                mask: "255.255.255.240"
```

Note the "append_to_tables" field which would define any table fields to which the provided entries should be appended, rather than the field being fully overwritten.  This would, however, introduce a race condition as it would have to GET, update, and then PUT the field value.  Would this be an acceptable solution in your case?
