### ISSUE TITLE
wrong interpretation of listen_on_traffic_ips

### ISSUE THREAD

**Issue by odumasFR** [mgeldert/pulse-vtm-ansible#3]
When I try to set the listening address of a virtual server on a specific trafficip_group, the resulting vserver listens to `* !vip_1`, which ends up in listening to every interface. 
I guess it may be another probem on the REST side, do you think I should raise an official ticket with support ?

```
---
- name: Create new vTM Config
  hosts: vtms
  tasks:
    - name: Define interfaces
      traffic_manager:
        name: "testLB"
        password: "{{ admin_password }}"
        properties:
          appliance:
            manageiptrans: True
            ip:
              - name: "ens160"
                addr: "10.1.1.1"
                isexternal: False
                mask: "255.255.255.240"
              - name: "ens192"
                addr: "10.0.0.1"
                isexternal: True
                mask: "255.255.255.0"

    - name: Traffic IP Groups
      traffic_ip_group:
        name: "vip_1"
        password: "{{ admin_password }}"
        properties:
          basic:
            enabled: True
            ipaddresses: [ "10.0.0.32" ]
            machines:  [ "testLB" ]

    - name: Create Virtual Servers
      virtual_server:
          name: "service_1"
          password: "{{ admin_password }}"
          properties:
              basic:
                  enabled: True
                  port: 80
                  pool: "discard"
                  listen_on_traffic_ips: [ "vip_1" ]
                  protocol: "http"

```
